### ISSUE TITLE
[Feature Request] Support for local gremlin servers

### ISSUE THREAD

**Issue by kpritam-tw** [aws-samples/amazon-neptune-generative-ai-samples#22]
Is it possible to make this more generic and allow any gremlin/opencypher supported databases?

For example, gremlin-server running on local machine.

```yaml
   gremlin-server:
       image: tinkerpop/gremlin-server:3.6.2
       container_name: gremlin_server
       ports:
         - 8182:8182
       mem_limit: 8g
       cpus: 8
       volumes:
         - ../database/conf/gremlin-server.yaml:/conf/gremlin-server.yaml
         - ../database/conf/tinkergraph-empty.properties:/conf/tinkergraph-empty.properties
```
